// ============================================
// LISTAS - Listas por curso con correos institucionales
// Asistencia 3D - Logos Academy
// Generado automaticamente desde indice_estudiantes_2026_2027.json
// ============================================

const LISTAS_CURSOS = {
  "Economia_3BGU": {
    label: "Economía 3BGU",
    color: "#2563eb",
    students: [
      { num: 1, name: "AGUILERA TERRANOVA ALEJANDRO NICOLAS", email: "ANaguilerat@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "ANDRADE GAROFALO EDUARDO NICOLAS", email: "ENandradeg@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "BRIONES PONCE OLENKA ELIZABETH", email: "oebrionesp@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 4, name: "CABRERA ALVEAR KAMILA ALEJANDRA", email: "KAcabreraa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "FLORES SANCHEZ PAULINA ALEJANDRA", email: "PAfloress@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "GARCÉS CABEZAS FIORELLA MICHELLE", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "GARCIA GALARZA FRANCISCO XAVIER", email: "fxgarciag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "GARRIDO LUNA MARTYN VICENTE", email: "MVgarridol@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "GAUNA CHÁVEZ VALERIE DENISSE", email: "vgaunac@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 10, name: "GOMEZ MARRIOTT ESTEFANO", email: "esgomezm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 11, name: "GUEDES LOOR RENATA VICTORIA", email: "rvguedesl12@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 12, name: "IÑIGUEZ FAJARDO ISABELLA VALENTINA", email: "IViniguezf@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "ITURRALDE CUMBA SANTIAGO ANDRES", email: "SAiturraldec@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "PERALTA AVILA SAMANTHA AGELENE", email: "SAperaltaa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "PLUA JARRIN CESAR EDUARDO", email: "cepluaj@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 16, name: "POZO CAJAS DAVID", email: "CDpozo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "TEJADA RUÍZ EMILY", email: "eetejadar@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 18, name: "TORRES MALDONADO EMILIA ALEJANDRA", email: "eatorresm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 19, name: "VELASCO SANTOS ALISSON ALESSANDRA", email: "aavelascos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 20, name: "VIZCAINO MACANCELA AMIR ANTONIO", email: "aavizcainom@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 21, name: "ZAMBRANO RIVERA DIANA ESTEFANIA", email: "DEzambranor@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "ZAMORA RODRIGUEZ GABRIEL ADRIAN", email: "GAzamorar@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "ZAMORA WONG KYLIE VALERIA", email: "KVzamoraw@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "ZUÑIGA BETTY DOMENICA VALENTINA", email: "dvzuniigab@logosacademy.edu.ec", fuente: "gmail_verificado" },
    ]
  },
  "Economia_2BGU": {
    label: "Economía 2BGU",
    color: "#7c3aed",
    students: [
      { num: 1, name: "ALBÁN ALTAMIRANO GIANELLA", email: "gaalbana@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "ASPIAZU SOTOMAYOR CAMILA", email: "", fuente: "" },
      { num: 3, name: "BARÓN MEJÍA JULIÁN", email: "MJbaron@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CAMPUZANO SALAZAR JUAN JOSÉ", email: "jjcampuzanos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 5, name: "CHALÉN HERRERA VICENTE", email: "vmchalenh11@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 6, name: "DE LA CRUZ NARANJO MATEO", email: "NMcruz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "FLOR LEÓN JACINTO", email: "LJflor@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "GRANDA CONSTANTINE XAVIER", email: "", fuente: "" },
      { num: 9, name: "GUERRERO HERDOÍZA IVANNA", email: "HIguerrero@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "MARTÍNEZ LUNA MATÍAS", email: "LMmartinez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "MENDIBURO CEDEÑO ADRIÁN", email: "CAmendiburo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MOLANO CASTRO EMMANUEL", email: "", fuente: "" },
      { num: 13, name: "MURILLO CHÁVEZ SERGIO", email: "CSmurillo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "ORTIZ EGAS SEBASTIÁN", email: "ESortiz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "ORTIZ MONTENEGRO CARLOS", email: "MCortiz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "PABÓN RENGIFO VALESKA", email: "vnpabonr@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 17, name: "ROMERO MONCADA JUAN MARTÍN", email: "", fuente: "" },
      { num: 18, name: "SIERRA TOALA ERNESTO", email: "TEsierra@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "STARK ROMÁN ALEJANDRA", email: "RAstark@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "TAMAYO BONILLA DOMENICA", email: "BDtamayo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VIZCAINO BONILLA JULIO", email: "BJvizcaino@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "VIZHÑAY VÉLEZ VALERIA", email: "VVvizhnay@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Economia_IB": {
    label: "Economía IB",
    color: "#ec4899",
    students: [
      { num: 1, name: "BRIONES PONCE OLENKA ELIZABETH", email: "oebrionesp@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "GARCÉS CABEZAS FIORELLA MICHELLE", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 3, name: "GARCIA GALARZA FRANCISCO XAVIER", email: "fxgarciag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 4, name: "GAUNA CHÁVEZ VALERIE DENISSE", email: "vgaunac@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 5, name: "GOMEZ MARRIOTT ESTEFANO", email: "esgomezm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 6, name: "GUEDES LOOR RENATA VICTORIA", email: "rvguedesl12@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "PLUA JARRIN CESAR EDUARDO", email: "cepluaj@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "TEJADA RUÍZ EMILY", email: "eetejadar@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 9, name: "TORRES MALDONADO EMILIA ALEJANDRA", email: "eatorresm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 10, name: "VELASCO SANTOS ALISSON ALESSANDRA", email: "aavelascos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 11, name: "VIZCAINO MACANCELA AMIR ANTONIO", email: "aavizcainom@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 12, name: "ZUÑIGA BETTY DOMENICA VALENTINA", email: "dvzuniigab@logosacademy.edu.ec", fuente: "gmail_verificado" },
    ]
  },
  "Historia_1BGU_A": {
    label: "Historia 1BGU A",
    color: "#059669",
    students: [
      { num: 1, name: "ALBAN ALTAMIRANO IVANNA FERNANDA", email: "gaalbana@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "ARTEAGA PLAZA MARIA EMILIA", email: "MEarteagap@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "BEJAR JIMENEZ HELENA VICTORIA", email: "HVbejarj@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CADENA RUIZ ABIGAIL", email: "RAcadena@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "CARDENAS ASTUDILLO JUAN ALEJANDRO", email: "JAcardenasa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "CARRILLO PEREZ MIGUEL ADRIAN", email: "MAcarrillop@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "CASTILLO RAMIREZ MARCO ANTONIO", email: "macastillor@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "CHONG QUI PEÑAFIEL MARIA EMILIA", email: "MEchongq@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "DEL SALTO PALACIOS MA. DEL MAR", email: "Msaltop@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "DIAZ VELIZ EDUARDO ANTONIO", email: "EAdiazv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "ESTRADA VERA ARIANA ISABEL", email: "AIestradav@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "FARFAN LEÓN LUCIANA SOFÍA", email: "LSfarfanl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "FERNANDEZ GONZABAY AMANDA ANNABELLA", email: "AAfernandezg@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "FIALLOS CONSTANTE BRUNO GABRIEL", email: "", fuente: "no_disponible" },
      { num: 15, name: "GALEFSKI MERINO ALANIS BELEN", email: "ABgalefskim@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "GARATE ANDRADE MANUEL ISAIAS", email: "MIgaratea@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "LEON HIDALGO JORGE ENRIQUE", email: "jeleonh@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 18, name: "MEDINA GOMEZ NICOLAS MARTIN", email: "nmmedinag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 19, name: "MEDINA MOREJON FABIANNA NICOLE", email: "FNmedinam@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "MOHR MOSCOL LUCAS AGUSTIN", email: "LAmohrm@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "MONCADA TAPIA PEDRO ARTURO", email: "pamoncadat@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 22, name: "MONTIEL CEDEÑO RUTH PAULETTE", email: "RPmontielc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "NAVIA ALCIVAR MIGUEL IVAN", email: "MInaviaa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "SALAZAR CAMPUZANO THELMO SAMUEL", email: "jjcampuzanos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 25, name: "VARGAS CARVAJAL MATIAS ADRIAN", email: "MAvargasc@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Historia_1BGU_B": {
    label: "Historia 1BGU B",
    color: "#d97706",
    students: [
      { num: 1, name: "CARDENAS VASQUEZ VALENTINA RAPHAELA", email: "VRcardenasv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "DARQUEA GUERRERO ISABELLA", email: "GIdarquea@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "DVORQUEZ SAMAN EITAN", email: "SEdvorquez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "ENCALADA ZAMBRANO PATRICK OLIVIER", email: "POencaladaz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "FLORES SANCHEZ VALENTINA", email: "SVflores@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "GARCÉS CABEZAS DOMÉNICA ISABELLA", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "GONZALEZ LOPEZ ISABELLA ALEJANDRA", email: "IAgonzalezl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "GONZALEZ VELASCO ESTEFANÍA", email: "VEgonzalez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "HIDALGO DROUET SAMANTHA", email: "DShidalgo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "HOYOS ESPIN AMANDA LIA", email: "ALhoyose@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "LABRE GALARZA RAFAELLA", email: "GRlabre@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MOSCOSO MARTINEZ ALICIA MARIA", email: "AMmoscosom@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "MUECKAY SALVATIERRA LUCAS XAVIER", email: "LXmueckays@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "NAHT MUÑOZ DOMENICA ANTONELLA", email: "DAnahtm@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "NARANJO OJEDA MAIHA", email: "OMnaranjo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "ORTIZ CABRERA DYLAN ANTONIO", email: "DAortizc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "RODRIGUEZ RUIZ DANNA VALERIA", email: "DVrodriguezr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 18, name: "SANTA CRUZ CERÓN MATTÍAS NICCOLO", email: "MNcruzc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "SOLORZANO SEBASTIAN", email: "ssolorzanor@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 20, name: "TAPIA GARZON ANDRES JESUS", email: "AJtapiag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VALLEJO HERDOIZA NICOLÁS ANDRES", email: "NAvallejoh@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "WENDT LANDIVAR NATHALIE FABIANA", email: "NFwendtl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "ZAMBRANO MOREIRA MARIA VICTORIA", email: "MVzambranom@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "ZAPATIER PEREZ LEONARDO", email: "PLzapatier@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Historia_1BGU_C": {
    label: "Historia 1BGU C",
    color: "#dc2626",
    students: [
      { num: 1, name: "ALAVA PONCE ISABELLA EDITH", email: "IEalavap@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "ALVARADO CASTRO RICARDO EDISON", email: "realvaradoc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 3, name: "BONILLA CHAVARRIA JUAN DIEGO", email: "JDbonillac@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CELLERI RAMIREZ FELIPE ALEJANDRO", email: "FAcellerir@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "CHACON REYES BELEN ALEJANDRA", email: "BAchaconr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "CRUZ PINEDA DOMENICA ALEJANDRA", email: "DAcruzp@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "DE LA CUADRA GARCES EILEEN ALBA", email: "EAcuadrag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "ENCALADA ZAMBRANO SURI POLETTE", email: "SPencaladaz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "GARCIA VELEZ GRACE VALENTINA", email: "GVgarciav@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "GAVILANES MENDEZ WILSON ADRIAN", email: "", fuente: "" },
      { num: 11, name: "GILER CAÑARTE LUCCIANA ISABELLE", email: "LIgilerc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MARTINEZ VELASQUEZ WLADIMIR ALEJANDRO", email: "WAmartinezv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "MORALES FLORES EMILIO ALEJANDRO", email: "EAmoralesf@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "OLIVEIRA YEPEZ ELIANE ANNELIESE", email: "EAoliveiray@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "PALACIOS RECALDE EDUARDO ANDRES", email: "EApalaciosr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "QUIMI CEDILLO KRYSTELL LISSET", email: "KLquimic@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "REINA SANCHEZ NISHMA VALENTINA", email: "NVreinas@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 18, name: "RIVADENEIRA LUZARDO AMANDA LUCIA", email: "ALrivadeneiral@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "RIVERA TINOCO ALEXA MARIA", email: "AMriverat@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "TOLEDO CASTILLO ROBERTO SEBASTIAN", email: "RStoledoc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VÉLEZ ZAMBRANO SAMUEL ENRIQUE", email: "SEvelezz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "VERA GILER DARMIN MATIAS", email: "DMverag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "YCAZA MONTJOY RICARDO XAVIER", email: "RXycazam@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
};

// Exportar para uso en el navegador
if (typeof window !== 'undefined') {
  window.LISTAS_CURSOS = LISTAS_CURSOS;
}
