// ============================================
// LISTAS - Listas por curso con correos institucionales
// Asistencia 3D - Logos Academy
// Generado automaticamente desde indice_estudiantes_2026_2027.json
// ============================================

const LISTAS_CURSOS = {
  "Economia_3BGU": {
    label: "Economía 3BGU",
    color: "#2563eb",
    students: [
      { num: 1, name: "AGUILERA TERRANOVA ALEJANDRO NICOLAS", email: "anaguilerat@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "ANDRADE GAROFALO EDUARDO NICOLAS", email: "enandradeg@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "BRIONES PONCE OLENKA ELIZABETH", email: "oebrionesp@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 4, name: "CABRERA ALVEAR KAMILA ALEJANDRA", email: "kacabreraa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "FLORES SANCHEZ PAULINA ALEJANDRA", email: "pafloress@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "GARCÉS CABEZAS FIORELLA MICHELLE", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "GARCIA GALARZA FRANCISCO XAVIER", email: "fxgarciag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "GARRIDO LUNA MARTYN VICENTE", email: "mvgarridol@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "GAUNA CHÁVEZ VALERIE DENISSE", email: "vgaunac@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 10, name: "GOMEZ MARRIOTT ESTEFANO", email: "esgomezm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 11, name: "GUEDES LOOR RENATA VICTORIA", email: "rvguedesl12@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 12, name: "IÑIGUEZ FAJARDO ISABELLA VALENTINA", email: "iviniguezf@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "ITURRALDE CUMBA SANTIAGO ANDRES", email: "saiturraldec@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "PERALTA AVILA SAMANTHA AGELENE", email: "saperaltaa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "PLUA JARRIN CESAR EDUARDO", email: "cepluaj@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 16, name: "POZO CAJAS DAVID", email: "cdpozo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "TEJADA RUÍZ EMILY", email: "eetejadar@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 18, name: "TORRES MALDONADO EMILIA ALEJANDRA", email: "eatorresm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 19, name: "VELASCO SANTOS ALISSON ALESSANDRA", email: "aavelascos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 20, name: "VIZCAINO MACANCELA AMIR ANTONIO", email: "aavizcainom@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 21, name: "ZAMBRANO RIVERA DIANA ESTEFANIA", email: "dezambranor@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "ZAMORA RODRIGUEZ GABRIEL ADRIAN", email: "gazamorar@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "ZAMORA WONG KYLIE VALERIA", email: "kvzamoraw@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "ZUÑIGA BETTY DOMENICA VALENTINA", email: "dvzuniigab@logosacademy.edu.ec", fuente: "gmail_verificado" },
    ]
  },
  "Economia_2BGU": {
    label: "Economía 2BGU",
    color: "#7c3aed",
    students: [
      { num: 1, name: "ALBÁN ALTAMIRANO GIANELLA", email: "gaalbana@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "ASPIAZU SOTOMAYOR CAMILA", email: "caaspiazus@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 3, name: "BARÓN MEJÍA JULIÁN", email: "mjbaron@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CAMPUZANO SALAZAR JUAN JOSÉ", email: "jjcampuzanos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 5, name: "CHALÉN HERRERA VICENTE", email: "vmchalenh11@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 6, name: "DE LA CRUZ NARANJO MATEO", email: "nmcruz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "FLOR LEÓN JACINTO", email: "ljflor@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "GRANDA CONSTANTINE XAVIER", email: "xagrandac@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 9, name: "GUERRERO HERDOÍZA IVANNA", email: "higuerrero@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "MARTÍNEZ LUNA MATÍAS", email: "lmmartinez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "MENDIBURO CEDEÑO ADRIÁN", email: "camendiburo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MOLANO CASTRO EMMANUEL", email: "emolanoc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 13, name: "MURILLO CHÁVEZ SERGIO", email: "smmurilloc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 14, name: "ORTIZ EGAS SEBASTIÁN", email: "esortiz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "ORTIZ MONTENEGRO CARLOS", email: "ceortizm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 16, name: "PABÓN RENGIFO VALESKA", email: "vnpabonr@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 17, name: "ROMERO MONCADA JUAN MARTÍN", email: "", fuente: "no_disponible" },
      { num: 18, name: "SIERRA TOALA ERNESTO", email: "tesierra@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "STARK ROMÁN ALEJANDRA", email: "rastark@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "TAMAYO BONILLA DOMENICA", email: "bdtamayo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VIZCAINO BONILLA JULIO", email: "bjvizcaino@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "VIZHÑAY VÉLEZ VALERIA", email: "vvvizhnay@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Economia_IB": {
    label: "Economía IB",
    color: "#ec4899",
    students: [
      { num: 1, name: "BRIONES PONCE OLENKA ELIZABETH", email: "oebrionesp@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "GARCÉS CABEZAS FIORELLA MICHELLE", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 3, name: "GARCIA GALARZA FRANCISCO XAVIER", email: "fxgarciag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 4, name: "GAUNA CHÁVEZ VALERIE DENISSE", email: "vgaunac@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 5, name: "GOMEZ MARRIOTT ESTEFANO", email: "esgomezm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 6, name: "GUEDES LOOR RENATA VICTORIA", email: "rvguedesl12@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "PLUA JARRIN CESAR EDUARDO", email: "cepluaj@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "TEJADA RUÍZ EMILY", email: "eetejadar@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 9, name: "TORRES MALDONADO EMILIA ALEJANDRA", email: "eatorresm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 10, name: "VELASCO SANTOS ALISSON ALESSANDRA", email: "aavelascos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 11, name: "VIZCAINO MACANCELA AMIR ANTONIO", email: "aavizcainom@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 12, name: "ZUÑIGA BETTY DOMENICA VALENTINA", email: "dvzuniigab@logosacademy.edu.ec", fuente: "gmail_verificado" },
    ]
  },
  "Historia_1BGU_A": {
    label: "Historia 1BGU A",
    color: "#059669",
    students: [
      { num: 1, name: "ALBAN ALTAMIRANO IVANNA FERNANDA", email: "gaalbana@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 2, name: "ARTEAGA PLAZA MARIA EMILIA", email: "mearteagap@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "BEJAR JIMENEZ HELENA VICTORIA", email: "hvbejarj@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CADENA RUIZ ABIGAIL", email: "racadena@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "CARDENAS ASTUDILLO JUAN ALEJANDRO", email: "jacardenasa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "CARRILLO PEREZ MIGUEL ADRIAN", email: "macarrillop@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "CASTILLO RAMIREZ MARCO ANTONIO", email: "macastillor@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 8, name: "CHONG QUI PEÑAFIEL MARIA EMILIA", email: "mechongq@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "DEL SALTO PALACIOS MA. DEL MAR", email: "msaltop@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "DIAZ VELIZ EDUARDO ANTONIO", email: "eadiazv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "ESTRADA VERA ARIANA ISABEL", email: "aiestradav@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "FARFAN LEÓN LUCIANA SOFÍA", email: "lsfarfanl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "FERNANDEZ GONZABAY AMANDA ANNABELLA", email: "aafernandezg@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "FIALLOS CONSTANTE BRUNO GABRIEL", email: "bgfiallosc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 15, name: "GALEFSKI MERINO ALANIS BELEN", email: "abgalefskim@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "GARATE ANDRADE MANUEL ISAIAS", email: "migaratea@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "LEON HIDALGO JORGE ENRIQUE", email: "jeleonh@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 18, name: "MEDINA GOMEZ NICOLAS MARTIN", email: "nmmedinag@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 19, name: "MEDINA MOREJON FABIANNA NICOLE", email: "fnmedinam@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "MOHR MOSCOL LUCAS AGUSTIN", email: "lamohrm@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "MONCADA TAPIA PEDRO ARTURO", email: "pamoncadat@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 22, name: "MONTIEL CEDEÑO RUTH PAULETTE", email: "rpmontielc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "NAVIA ALCIVAR MIGUEL IVAN", email: "minaviaa@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "SALAZAR CAMPUZANO THELMO SAMUEL", email: "jjcampuzanos@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 25, name: "VARGAS CARVAJAL MATIAS ADRIAN", email: "mavargasc@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Historia_1BGU_B": {
    label: "Historia 1BGU B",
    color: "#d97706",
    students: [
      { num: 1, name: "CARDENAS VASQUEZ VALENTINA RAPHAELA", email: "vrcardenasv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "DARQUEA GUERRERO ISABELLA", email: "gidarquea@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 3, name: "DVORQUEZ SAMAN EITAN", email: "sedvorquez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "ENCALADA ZAMBRANO PATRICK OLIVIER", email: "poencaladaz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "FLORES SANCHEZ VALENTINA", email: "svflores@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "GARCÉS CABEZAS DOMÉNICA ISABELLA", email: "fgarcesc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 7, name: "GONZALEZ LOPEZ ISABELLA ALEJANDRA", email: "iagonzalezl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "GONZALEZ VELASCO ESTEFANÍA", email: "vegonzalez@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "HIDALGO DROUET SAMANTHA", email: "dshidalgo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "HOYOS ESPIN AMANDA LIA", email: "alhoyose@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 11, name: "LABRE GALARZA RAFAELLA", email: "grlabre@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MOSCOSO MARTINEZ ALICIA MARIA", email: "ammoscosom@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "MUECKAY SALVATIERRA LUCAS XAVIER", email: "lxmueckays@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "NAHT MUÑOZ DOMENICA ANTONELLA", email: "danahtm@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "NARANJO OJEDA MAIHA", email: "omnaranjo@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "ORTIZ CABRERA DYLAN ANTONIO", email: "daortizc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "RODRIGUEZ RUIZ DANNA VALERIA", email: "dvrodriguezr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 18, name: "SANTA CRUZ CERÓN MATTÍAS NICCOLO", email: "mncruzc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "SOLORZANO SEBASTIAN", email: "ssolorzanor@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 20, name: "TAPIA GARZON ANDRES JESUS", email: "ajtapiag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VALLEJO HERDOIZA NICOLÁS ANDRES", email: "navallejoh@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "WENDT LANDIVAR NATHALIE FABIANA", email: "nfwendtl@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "ZAMBRANO MOREIRA MARIA VICTORIA", email: "mvzambranom@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 24, name: "ZAPATIER PEREZ LEONARDO", email: "plzapatier@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
  "Historia_1BGU_C": {
    label: "Historia 1BGU C",
    color: "#dc2626",
    students: [
      { num: 1, name: "ALAVA PONCE ISABELLA EDITH", email: "iealavap@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 2, name: "ALVARADO CASTRO RICARDO EDISON", email: "realvaradoc@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 3, name: "BONILLA CHAVARRIA JUAN DIEGO", email: "jdbonillac@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 4, name: "CELLERI RAMIREZ FELIPE ALEJANDRO", email: "facellerir@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 5, name: "CHACON REYES BELEN ALEJANDRA", email: "bachaconr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 6, name: "CRUZ PINEDA DOMENICA ALEJANDRA", email: "dacruzp@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 7, name: "DE LA CUADRA GARCES EILEEN ALBA", email: "eacuadrag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 8, name: "ENCALADA ZAMBRANO SURI POLETTE", email: "spencaladaz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 9, name: "GARCIA VELEZ GRACE VALENTINA", email: "gvgarciav@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 10, name: "GAVILANES MENDEZ WILSON ADRIAN", email: "wagavilanesm@logosacademy.edu.ec", fuente: "gmail_verificado" },
      { num: 11, name: "GILER CAÑARTE LUCCIANA ISABELLE", email: "ligilerc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 12, name: "MARTINEZ VELASQUEZ WLADIMIR ALEJANDRO", email: "wamartinezv@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 13, name: "MORALES FLORES EMILIO ALEJANDRO", email: "eamoralesf@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 14, name: "OLIVEIRA YEPEZ ELIANE ANNELIESE", email: "eaoliveiray@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 15, name: "PALACIOS RECALDE EDUARDO ANDRES", email: "eapalaciosr@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 16, name: "QUIMI CEDILLO KRYSTELL LISSET", email: "klquimic@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 17, name: "REINA SANCHEZ NISHMA VALENTINA", email: "nvreinas@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 18, name: "RIVADENEIRA LUZARDO AMANDA LUCIA", email: "alrivadeneiral@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 19, name: "RIVERA TINOCO ALEXA MARIA", email: "amriverat@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 20, name: "TOLEDO CASTILLO ROBERTO SEBASTIAN", email: "rstoledoc@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 21, name: "VÉLEZ ZAMBRANO SAMUEL ENRIQUE", email: "sevelezz@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 22, name: "VERA GILER DARMIN MATIAS", email: "dmverag@logosacademy.edu.ec", fuente: "patron_predicho" },
      { num: 23, name: "YCAZA MONTJOY RICARDO XAVIER", email: "rxycazam@logosacademy.edu.ec", fuente: "patron_predicho" },
    ]
  },
};

// Exportar para uso en el navegador
if (typeof window !== 'undefined') {
  window.LISTAS_CURSOS = LISTAS_CURSOS;
}
